<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('AuditLogs', function (Blueprint $table) {

            // Primary key
            $table->id('Id'); // bigint auto-increment
            // Using PostgreSQL GENERATED BY DEFAULT AS IDENTITY handled automatically by bigIncrements in Laravel

            // Columns
            $table->uuid('UserId')->nullable();
            $table->string('Action', 100);
            $table->string('AuditableType', 100);
            $table->string('AuditableId', 50)->nullable();
            $table->text('OldValues')->nullable();
            $table->text('NewValues')->nullable();
            $table->string('IpAddress', 50)->nullable();
            $table->string('Location', 200)->nullable();
            $table->timestampTz('CreatedAt')->default(DB::raw('now()'));
            $table->timestampTz('UpdatedAt')->default(DB::raw('now()'));
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('AuditLogs');
    }
};
